image: golang:latest

variables:
  TARGET: /www/bin/jarvis

stages:
  - test
  - build
  - deploy
  - sync

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - go build -o binary
  artifacts:
    paths:
      - binary

sync:
  stage: sync
  tags:
    - tencent
  script:
    - rm -rf $TARGET
    - cp binary $TARGET
    - chmod +x $TARGET
