#--------------------------------------------------
#  开发环境
#--------------------------------------------------
#

version: '3.9'
services:
  app:
    build:
      context: ./
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    command: tail -f /dev/null
