---
#--------------------------------------------------
#  发布到生产环境
#--------------------------------------------------
#

name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main, develop]
    tags:
      - "*"

jobs:
  deploy:
    uses: 585Api/workflows/.github/workflows/deploy_go.yaml@main
